apiVersion: v1
kind: Pod
metadata:
  name: pod-1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: my-app
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
